// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import BottomNavigationController from "./bottom_navigation_controller"
application.register("bottom-navigation", BottomNavigationController)

import ClickableCardController from "./clickable_card_controller"
application.register("clickable-card", ClickableCardController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GlobalAudioPlayerController from "./global_audio_player_controller"
application.register("global-audio-player", GlobalAudioPlayerController)

import NavigationTabsController from "./navigation_tabs_controller"
application.register("navigation-tabs", NavigationTabsController)

import PodcastFormController from "./podcast_form_controller"
application.register("podcast-form", PodcastFormController)

import SearchableDropdownController from "./searchable_dropdown_controller"
application.register("searchable-dropdown", SearchableDropdownController)
