// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BottomNavigationController from "./bottom_navigation_controller"
application.register("bottom-navigation", BottomNavigationController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import PageTransitionController from "./page_transition_controller"
application.register("page-transition", PageTransitionController)

import PodcastFormController from "./podcast_form_controller"
application.register("podcast-form", PodcastFormController)
