##
# Podcast model represents a single audio podcast episode generated from a source document
#
# Podcasts belong to a creator (User) and can have multiple authors and publishers.
# They support file attachments for source PDFs and generated audio files.
# Full-text search is enabled across title, issn, doi, and related author/publisher names.
#
# @attr [String] title - The main title of the podcast (unique)
# @attr [String] issn - The ISSN of the source material (optional)
# @attr [String] doi - The DOI of the source material (optional, unique)
# @attr [Text] summary - A short summary of the podcast content (optional)
# @attr [Text] script - The full text script used for audio generation (optional)
# @attr [String] audio_url - S3 URL for the generated audio file (optional)
# @attr [Integer] user_id - Foreign key to the creating user
# @attr [String] status - Processing status: 'processing', 'ready', 'error', 'cancelled' (PostgreSQL enum)
# @attr [String] status_details - Processing detail string: "", "processing_source_file", "generating_script", "generating_audio_file"
# @attr [DateTime] created_at - When the podcast was created
# @attr [DateTime] updated_at - When the podcast was last updated
#
class Podcast < ApplicationRecord
  include PgSearch::Model

  # Relationships
  belongs_to :user

  # Many-to-many relationships
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :publishers
  has_and_belongs_to_many :categories

  # Favorites relationship
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user

  # File attachments using Active Storage
  has_one_attached :source_file  # Original PDF document
  # Audio is now stored as URL (audio_url column) in S3, not as attachment

  # Enums for status management using PostgreSQL enum
  enum :status, {
    processing: 'processing',
    ready: 'ready',
    error: 'error',
    cancelled: 'cancelled'
  }, default: 'processing'

  # Validations
  # Title, DOI, and other metadata will be generated by AI
  validates :doi, uniqueness: { allow_blank: true }
  validates :status_details, inclusion: {
    in: [ "", "processing_source_file", "generating_script", "generating_audio_file" ],
    allow_blank: true
  }
  validates :audio_url, format: { with: URI::DEFAULT_PARSER.make_regexp, allow_blank: true }

  # File validations will be handled in the controller and with custom methods
  validate :validate_source_file, if: -> { source_file.attached? }
  # Audio file validation removed

  # Search configuration using pg_search
  pg_search_scope :search_by_content,
    against: [ :title, :issn, :doi ],
    associated_against: {
      authors: [ :name ]
    },
    using: {
      tsearch: {
        prefix: true,
        negation: true,
        dictionary: :english
      }
    }

  # Scopes for common queries
  scope :recent, -> { order(created_at: :desc) }
  scope :by_status, ->(status) { where(status: status) }
  scope :published, -> { where(status: [ :ready ]) }
  
  # N+1 Query Optimizations
  scope :with_favorites_for_user, ->(user) {
    if user
      left_joins(:favorites)
        .select("podcasts.*, COUNT(favorites.id) as favorites_count")
        .select("BOOL_OR(favorites.user_id = #{user.id}) as user_favorited")
        .group("podcasts.id")
    else
      left_joins(:favorites)
        .select("podcasts.*, COUNT(favorites.id) as favorites_count") 
        .select("false as user_favorited")
        .group("podcasts.id")
    end
  }

  # File validation helper
  def validate_source_file
    return unless source_file.attached?

    unless source_file.content_type == 'application/pdf'
      errors.add(:source_file, 'must be a PDF file')
    end

    # Check file size (limit to 50MB)
    if source_file.byte_size > 50.megabytes
      errors.add(:source_file, 'must be less than 50MB')
    end
  end

  ##
  # Check if a specific user has favorited this podcast
  # Uses preloaded value to avoid N+1 queries
  #
  # @param [User] user - The user to check
  # @return [Boolean] true if favorited, false otherwise
  #
  def favorited_by_user?(user)
    return false unless user
    
    # Use preloaded value if available (from with_favorites_for_user scope)
    if has_attribute?(:user_favorited)
      read_attribute(:user_favorited)
    else
      # Fallback to association query
      favorites.exists?(user: user)
    end
  end

  ##
  # Get a display-friendly duration for the audio file
  #
  # @return [String] formatted duration or "Unknown" if no audio
  #
  def audio_duration
    # This would be implemented with audio metadata extraction
    # For now, return a placeholder
    "Unknown"
  end

  ##
  # Check if the podcast has a complete set of files (source + audio)
  #
  # @return [Boolean] true if both source and audio files are attached
  #
  def complete?
    source_file.attached? && audio_url.present?
  end

  ##
  # Get the count of favorites for this podcast
  # Uses preloaded count from with_favorites_for_user scope if available,
  # otherwise performs a COUNT query
  #
  # @return [Integer] number of times this podcast has been favorited
  #
  def favorites_count
    # If favorites_count was preloaded by with_favorites_for_user scope, use it
    if has_attribute?(:favorites_count) && read_attribute(:favorites_count)
      read_attribute(:favorites_count)
    else
      # Fallback to COUNT query if not preloaded
      favorites.count
    end
  end

  private

  ##
  # Scope for finding podcasts by a specific user
  #
  # @param [User] user - The user to filter by
  # @return [ActiveRecord::Relation] podcasts created by the user
  #
  scope :by_user, ->(user) { where(user: user) }

  ##
  # Scope for finding favorited podcasts by a specific user
  #
  # @param [User] user - The user whose favorites to find
  # @return [ActiveRecord::Relation] podcasts favorited by the user
  #
  scope :favorited_by, ->(user) {
    joins(:favorites).where(favorites: { user: user })
  }

  ##
  # Scope for ordering by most favorited
  #
  # @return [ActiveRecord::Relation] podcasts ordered by favorite count (most favorited first)
  #
  scope :most_favorited, -> {
    left_joins(:favorites)
      .group(:id)
      .order('COUNT(favorites.id) DESC')
  }

  ##
  # Scope for finding podcasts by a specific status detail
  #
  # @param [String] status_details - The status detail to filter by
  # @return [ActiveRecord::Relation] podcasts with the specified status detail
  #
  scope :by_status_details, ->(status_details) { where(status_details: status_details) }
end
