##
# Podcast model represents a single audio podcast episode generated from a source document
#
# Podcasts belong to a creator (User) and can have multiple authors and publishers.
# They support file attachments for source PDFs and generated audio files.
# Full-text search is enabled across title, issn, doi, and related author/publisher names.
#
# @attr [String] title - The main title of the podcast (unique)
# @attr [String] issn - The ISSN of the source material (optional)
# @attr [String] doi - The DOI of the source material (optional, unique)
# @attr [Text] summary - A short summary of the podcast content (optional)
# @attr [Text] script - The full text script used for audio generation (optional)
# @attr [Integer] user_id - Foreign key to the creating user
# @attr [String] status - Processing status: 'processing', 'ready', 'error', 'cancelled' (PostgreSQL enum)
# @attr [String] status_details - Processing detail string: "", "processing_source_file", "generating_script", "generating_audio_file"
# @attr [DateTime] created_at - When the podcast was created
# @attr [DateTime] updated_at - When the podcast was last updated
#
class Podcast < ApplicationRecord
  include PgSearch::Model

  # Relationships
  belongs_to :user, class_name: 'User'

  # Many-to-many relationships
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :publishers

  # Favorites relationship
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user

  # File attachments using Active Storage
  has_one_attached :source_file  # Original PDF document
  has_one_attached :audio        # Generated audio file (MP3, M4A, etc.)

  # Enums for status management using PostgreSQL enum
  enum :status, {
    processing: 'processing',
    ready: 'ready',
    error: 'error',
    cancelled: 'cancelled'
  }, default: 'processing'

  # Validations
  # Title, DOI, and other metadata will be generated by AI
  validates :doi, uniqueness: { allow_blank: true }
  validates :status_details, inclusion: { 
    in: ["", "processing_source_file", "generating_script", "generating_audio_file"], 
    allow_blank: true 
  }

  # File validations will be handled in the controller and with custom methods
  validate :validate_source_file, if: -> { source_file.attached? }
  validate :validate_audio_file, if: -> { audio.attached? }

  # Search configuration using pg_search
  pg_search_scope :search_by_content,
    against: [ :title, :issn, :doi, :summary ],
    associated_against: {
      authors: [ :name ],
      publishers: [ :name ]
    },
    using: {
      tsearch: {
        prefix: true,
        highlight: {
          start_sel: '<mark>',
          stop_sel: '</mark>'
        }
      }
    }

  ##
  # Check if a podcast is favorited by a specific user
  #
  # @param [User] user - The user to check
  # @return [Boolean] true if favorited by user, false otherwise
  #
  def favorited_by?(user)
    return false unless user
    favorited_by_users.include?(user)
  end

  ##
  # Get the count of users who have favorited this podcast
  #
  # @return [Integer] number of favorites
  #
  delegate :count, to: :favorites, prefix: true

  ##
  # Get a display-friendly duration for the audio file
  #
  # @return [String] formatted duration or "Unknown" if no audio
  #
  def audio_duration
    # This would be implemented with audio metadata extraction
    # For now, return a placeholder
    audio.attached? ? "Unknown duration" : "No audio"
  end

  ##
  # Check if the podcast has a complete set of files (source + audio)
  #
  # @return [Boolean] true if both source and audio files are attached
  #
  def complete?
    source_file.attached? && audio.attached?
  end

  private

  ##
  # Validate source file type and size
  #
  def validate_source_file
    return unless source_file.attached?

    # Check file type
    unless source_file.content_type == 'application/pdf'
      errors.add(:source_file, 'must be a PDF file')
    end

    # Check file size (50MB limit)
    if source_file.byte_size > 50.megabytes
      errors.add(:source_file, 'must be less than 50MB')
    end
  end

  ##
  # Validate audio file type and size
  #
  def validate_audio_file
    return unless audio.attached?

    # Check file type
    allowed_audio_types = [ 'audio/mpeg', 'audio/mp4', 'audio/wav', 'audio/x-m4a', 'audio/mp3' ]
    unless allowed_audio_types.include?(audio.content_type)
      errors.add(:audio, 'must be an audio file (MP3, MP4, WAV, M4A)')
    end

    # Check file size (100MB limit)
    if audio.byte_size > 100.megabytes
      errors.add(:audio, 'must be less than 100MB')
    end
  end

  ##
  # Scope for finding podcasts by a specific user
  #
  # @param [User] user - The user to filter by
  # @return [ActiveRecord::Relation] podcasts created by the user
  #
  scope :by_user, ->(user) { where(user: user) }

  ##
  # Scope for finding favorited podcasts by a specific user
  #
  # @param [User] user - The user whose favorites to find
  # @return [ActiveRecord::Relation] podcasts favorited by the user
  #
  scope :favorited_by, ->(user) {
    joins(:favorites).where(favorites: { user: user })
  }

  ##
  # Scope for ordering by most recently created
  #
  # @return [ActiveRecord::Relation] podcasts ordered by creation date (newest first)
  #
  scope :recent, -> { order(created_at: :desc) }

  ##
  # Scope for ordering by most favorited
  #
  # @return [ActiveRecord::Relation] podcasts ordered by favorite count (most favorited first)
  #
  scope :most_favorited, -> {
    left_joins(:favorites)
      .group(:id)
      .order('COUNT(favorites.id) DESC')
  }

  ##
  # Scope for finding podcasts by a specific status
  #
  # @param [Integer] status - The status to filter by (0, 1, or 2)
  # @return [ActiveRecord::Relation] podcasts with the specified status
  #
  scope :by_status, ->(status) { where(status: status) }

  ##
  # Scope for finding podcasts by a specific status detail
  #
  # @param [String] status_details - The status detail to filter by
  # @return [ActiveRecord::Relation] podcasts with the specified status detail
  #
  scope :by_status_details, ->(status_details) { where(status_details: status_details) }
end
